name: bookthera_customer
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.5+18

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Required
  intl: ^0.17.0
  nb_utils: ^4.6.20
  cached_network_image: ^3.2.1
  loading_indicator: ^3.1.0
  pin_code_fields: ^7.4.0
  flutter_rating_bar: ^4.0.1
  table_calendar: ^3.0.8
  photo_view: ^0.14.0
  emoji_picker_flutter: ^1.5.1
  agora_rtc_engine: ^6.2.2
  web_socket_channel: ^2.3.0
  percent_indicator: ^4.2.2
  readmore: ^2.2.0
  intl_phone_field: ^3.1.0
  flutter_braintree: ^3.0.0
  
  # API call
  http: ^0.13.5

  # State Management
  provider: ^6.0.5

  # Launch url
  url_launcher: ^6.1.5

  # Image selection
  image_picker: ^0.8.5+3
  image: 

  # Web-views
  webview_flutter: ^3.0.4

  # File Download
  permission_handler: ^10.0.0

  # Local storage path
  path_provider: ^2.0.11

  # Firebase remote config
  firebase_core: ^1.21.1
  firebase_auth: 
  google_sign_in: 5.3.3
  firebase_core_platform_interface: 4.5.1 
  firebase_messaging: 

  flutter_localizations:
    sdk: flutter
  package_info_plus: ^4.2.0
  firebase_dynamic_links: ^4.3.11


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  #flutter packages pub run build_runner build

dependency_overrides:
  video_player: 2.1.12

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
  
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_icon.png"